/*****************************************************************************************************
 
Class    :  
Developer:  Kiril Minev
Created  :  
Modified :  
Objective:  
 
*****************************************************************************************************/
@isTest
private class cls_Payment_Automation_Service_Test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
    }
}