public class skedConstants {
    public static final string ACCCOUNT_SCORE_BLACKLIST = 'Blacklist';
    public static final string ACCCOUNT_SCORE_WHITELIST = 'Whitelist';

    public static final string AVAILABILITY_STATUS_APPROVED = 'Approved';
    public static final string AVAILABILITY_STATUS_PENDING = 'Pending';
    public static final string AVAILABILITY_STATUS_DECLINED = 'Declined';

    public static final string COMMUNITY_CLASS_SUB_TYPE_BASE = 'Base';
    public static final string COMMUNITY_CLASS_SUB_TYPE_BASE_ADD_ON = 'Base Add On';

    public static final string COMMUNITY_COPY_ROOM_CONFLICT = 'Room Conflict';
    public static final string COMMUNITY_COPY_OUT_OF_MONTH = 'Out of month';
    
    public static final string COURSE_CATALOG_TYPE_FULL_SERVICE = 'Full Service';
    public static final string COURSE_CATALOG_TYPE_COMMUNITY = 'Community';
    public static final string COURSE_CATALOG_TYPE_NURSE_ASSISTANT_TESTING = 'Nurse Assistant Testing';
    public static final string COURSE_CATALOG_TYPE_NURSE_ASSISTANT_TRAINING = 'Nurse Assistant Training';

    public static final string EVENT_TYPE_OTHER = 'Other';

    public static final string JOB_STATUS_CANCELLED = 'Cancelled';
    public static final string JOB_STATUS_COMPLETE = 'Complete';
    public static final string JOB_STATUS_DISPATCHED = 'Dispatched';
    public static final string JOB_STATUS_IN_PROGRESS = 'In Progress';
    public static final string JOB_STATUS_PENDING_ALLOCATION = 'Pending Allocation';
    public static final string JOB_STATUS_PENDING_DISPATCH = 'Pending Dispatch';
    public static final string JOB_STATUS_QUEUED = 'Queued';
    public static final string JOB_STATUS_READY = 'Ready';
    public static final string JOB_STATUS_ON_SITE = 'On Site';
    public static final string JOB_STATUS_EN_ROUTE = 'En Route';
    
    public static final string JOB_TYPE_FULL_SERVICE = 'Full Service';
    public static final string JOB_TYPE_COMMUNITY = 'Community';
    public static final string JOB_TYPE_NURSE_ASSISTANT_TESTING = 'Nurse Assistant Testing';
    public static final string JOB_TYPE_NURSE_ASSISTANT_TESTING_FULL_SERVICE = 'Nurse Assistant Testing - Full Service';
    public static final string JOB_TYPE_NURSE_ASSISTANT_TRAINING = 'Nurse Assistant Training';
    public static final string JOB_TYPE_NURSE_ASSISTANT_TRAINING_FULL_SERVICE = 'Nurse Assistant Training - Full Service';
    
    public static final string JOB_ALLOCATION_STATUS_COMPLETE = 'Complete';
    public static final string JOB_ALLOCATION_STATUS_CONFIRMED = 'Confirmed';
    public static final string JOB_ALLOCATION_STATUS_DECLINED = 'Declined';
    public static final string JOB_ALLOCATION_STATUS_DELETED = 'Deleted';
    public static final string JOB_ALLOCATION_STATUS_DISPATCHED = 'Dispatched';
    public static final string JOB_ALLOCATION_STATUS_PENDING_DISPATCH = 'Pending Dispatch';
    public static final string JOB_ALLOCATION_STATUS_EN_ROUTE = 'En Route';
    public static final string JOB_ALLOCATION_STATUS_CHECKED_IN = 'Checked In';
    public static final string JOB_ALLOCATION_STATUS_IN_PROGRESS = 'In Progress';
    
    public static final string LOCATION_TYPE_FULL_SERVICE = 'Full Service';
    public static final string LOCATION_TYPE_COMMUNITY = 'Community';
    public static final string LOCATION_TYPE_COMMUNITY_TEMP = 'Community Temp';
    public static final string LOCATION_TYPE_NURSE_ASSISTANT_TESTING = 'Nurse Assistant Testing';
    public static final string LOCATION_TYPE_NURSE_ASSISTANT_TRAINING = 'Nurse Assistant Training';
    public static final string LOCATION_TYPE_NAT_AND_CEP = 'NAT and CEP';
    public static final string LOCATION_TYPE_NAT_AND_COMMUNITY = 'NAT and Community';
    public static final string LOCATION_TYPE_INTERNAL = 'Internal';
    
    public static final string RESOURCE_EMPLOYMENT_TYPE_SUBCONTRACTOR = 'Subcontractor';
    
    public static final string RESOURCE_CATEGORY_EVALUATOR = 'Evaluator';
    public static final string RESOURCE_CATEGORY_CHARGE_NURSE = 'Charge Nurse';
    public static final string RESOURCE_CATEGORY_PROCTOR = 'Proctor';
    public static final string RESOURCE_CATEGORY_INSTRUCTOR = 'Instructor';
    public static final string RESOURCE_CATEGORY_NURSE_INSTRUCTOR = 'Nurse Instructor';

    public static final string TRAINING_EVENT_WRITTEN_TEST_YES = 'Yes';
    public static final string TRAINING_EVENT_WRITTEN_TEST_NO = 'No';

    public static final string ARC_USER_TYPE_DIVISION_SCHEDULER = 'Division Scheduler';
    public static final string ARC_USER_TYPE_SECONDARY_SCHEDULER = 'Secondary Scheduler';
    public static final string ARC_USER_TYPE_READ_ONLY_SCHEDULER = 'Read Only Scheduler';
    
    public static final string HOLIDAY_GLOBAL = 'global';

}